"""Curated regional slang extensions for the Sahara AI safety parser.

This module intentionally separates supplied slang/pharma batches from the
clinical profiles in ``sahara_ai_protocol.py``. The batches contain useful
terms, but also ordinary English words, generic hookah hardware, and claims
that need stronger source validation. Ambiguous terms use strength=1 so they
only match when the message also contains substance-use context such as nasha,
high, dose, smoke, talab, overdose, etc.
"""

from __future__ import annotations

from typing import Dict, Tuple


AliasSpec = Tuple[str, int]


REGIONAL_SLANG_ALIASES_BY_PROFILE: Dict[str, Tuple[AliasSpec, ...]] = {
    "Ice / Methamphetamine": (
        (r"tik[\s\-]*tik", 2),
        (r"kaan+ch", 2),
        (r"safed", 1),
    ),
    "Synthetic stimulants / Cathinones / Captagon": (
        (r"captagon", 2),
        (r"fenethylline", 2),
        (r"tablet[\s\-]*k", 2),
        (r"bath\s+salts?", 2),
        (r"flakka", 2),
        (r"alpha[\s\-]*pvp", 2),
        (r"a[\s\-]*pvp", 2),
        (r"gravel", 1),
        (r"cloud\s+nine", 2),
        (r"cloud\s+9", 2),
        (r"ivory\s+wave", 2),
        (r"vanilla\s+sky", 2),
        (r"bloom", 1),
        (r"scarface", 1),
        (r"monkey\s+dust", 2),
        (r"meow[\s\-]*meow", 2),
        (r"m[\s\-]*cat", 2),
        (r"mephedrone", 2),
        (r"drone", 1),
        (r"bubble", 1),
        (r"legal\s+high", 2),
        (r"research\s+chemical", 2),
        (r"designer\s+drug", 2),
        (r"party\s+pill", 2),
        (r"rc", 1),
    ),
    "PCP / Angel Dust": (
        (r"angel\s+dust", 2),
        (r"phencyclidine", 2),
        (r"pcp", 2),
    ),
    "Heroin / Opioids": (
        (r"krokodil", 2),
        (r"desomorphine", 2),
        (r"dilaudid", 2),
        (r"hydromorphone", 2),
        (r"dilly", 1),
        (r"morphine", 2),
        (r"ms\s+contin", 2),
        (r"white\s+stuff", 2),
        (r"no\.?\s*4", 2),
        (r"no\.?\s*3", 2),
        (r"morphine\s+base", 2),
        (r"crude\s+base", 2),
        (r"kalakot", 2),
        (r"afghan\s+black", 2),
        (r"patthar", 1),
        (r"china\s+white", 2),
        (r"alpha[\s\-]*methylfentanyl", 2),
        (r"dance\s+fever", 1),
        (r"goodfellas", 1),
        (r"murder\s*8", 2),
        (r"nubain", 2),
        (r"nalbuphine", 2),
        (r"stadol", 2),
        (r"butorphanol", 2),
        (r"talwin", 2),
        (r"pentazocine", 2),
        (r"t'?s\s+and\s+blues", 2),
        (r"buprenex", 2),
        (r"subutex", 2),
        (r"suboxone", 2),
        (r"bupe", 2),
        (r"buprenorphine", 2),
        (r"methadone", 2),
        (r"dolly", 1),
        (r"fizze", 2),
        (r"dezocine", 2),
        (r"dalgan", 2),
        (r"sufenta", 2),
        (r"sufentanil", 2),
        (r"remi", 1),
        (r"remifentanil", 2),
        (r"alfenta", 2),
        (r"alfentanil", 2),
        (r"carfentanil", 2),
        (r"u[\s\-]*47700", 2),
        (r"pink", 1),
        (r"mt[\s\-]*45", 2),
        (r"ah[\s\-]*7921", 2),
        (r"isotonitazene", 2),
        (r"iso", 1),
        (r"metonitazene", 2),
        (r"etonitazene", 2),
        (r"protonitazene", 2),
        (r"brorphine", 2),
        (r"benzylfentanyl", 2),
        (r"thf[\s\-]*f", 2),
        (r"tetrahydrofuranylfentanyl", 2),
        (r"cyclopropylfentanyl", 2),
        (r"crotonylfentanyl", 2),
        (r"valeryl\s+fentanyl", 2),
        (r"acrylfentanyl", 2),
        (r"furanylfentanyl", 2),
        (r"para[\s\-]*fluorofentanyl", 2),
        (r"4[\s\-]*fmf", 2),
        (r"ocfentanil", 2),
        (r"loperamide\s+high[\s\-]*dose", 2),
        (r"imodium\s+abuse", 2),
        (r"poor\s+man'?s\s+methadone", 2),
    ),
    "Atypical opioids / Kratom / Tianeptine": (
        (r"kratom", 2),
        (r"mitragynine", 2),
        (r"7[\s\-]*oh", 2),
        (r"7[\s\-]*hydroxymitragynine", 2),
        (r"korthals", 1),
        (r"biak[\s\-]*biak", 2),
        (r"ketum", 2),
        (r"thom", 1),
        (r"tianeptine", 2),
        (r"gas\s+station\s+heroin", 2),
        (r"coaxil", 2),
        (r"zaza", 2),
        (r"red\s+dawn", 1),
    ),
    "Unprescribed opioid pills / Tramadol": (
        (r"trama", 2),
        (r"t[\s\-]*plus", 2),
        (r"rydol", 2),
        (r"oxycontin", 2),
        (r"oxycodone", 2),
        (r"percs?", 2),
        (r"percocet", 2),
        (r"vics", 1),
        (r"vicodin", 2),
        (r"norco", 2),
        (r"lortab", 2),
        (r"roxys?", 2),
        (r"roxicodone", 2),
        (r"tylenol\s*3", 2),
        (r"t3s", 2),
        (r"empirin", 2),
        (r"tapentadol", 2),
        (r"nucynta", 2),
    ),
    "Sedatives / Z-drugs / Barbiturates / Muscle relaxants": (
        (r"phenibut", 2),
        (r"noofen", 2),
        (r"picamilon", 2),
        (r"chloral\s+hydrate", 2),
        (r"knockout\s+drops", 2),
        (r"mickey\s+finn", 2),
        (r"barbiturates?", 2),
        (r"phenobarb", 2),
        (r"phenobarbital", 2),
        (r"luminal", 2),
        (r"seconal", 2),
        (r"reds", 1),
        (r"tuinal", 2),
        (r"blue\s+heaven", 2),
        (r"amytal", 2),
        (r"meprobamate", 2),
        (r"equanil", 2),
        (r"miltown", 2),
        (r"carisoprodol", 2),
        (r"soma", 1),
        (r"trance", 1),
        (r"cyclobenzaprine", 2),
        (r"flexeril", 2),
        (r"baclofen", 2),
        (r"lioresal", 2),
        (r"zolpidem", 2),
        (r"ambien", 2),
        (r"z[\s\-]*drugs?", 2),
        (r"eszopiclone", 2),
        (r"lunesta", 2),
        (r"zaleplon", 2),
        (r"sonata", 2),
    ),
    "Unprescribed Xanax / Benzodiazepines": (
        (r"xanies", 2),
        (r"bars", 1),
        (r"blue(?:s)?", 1),
        (r"vallies", 2),
        (r"diya", 1),
        (r"lexo", 2),
        (r"rivo", 2),
        (r"k[\s\-]*pin", 2),
        (r"lori", 1),
        (r"erimin", 2),
        (r"five[\s\-]*five", 2),
        (r"roche", 1),
        (r"roof(?:ie|ies)", 2),
        (r"dormicum", 2),
        (r"dormi", 2),
        (r"flunitrazepam", 2),
        (r"midazolam", 2),
        (r"nimetazepam", 2),
    ),
    "Cough syrup / Dextromethorphan or Codeine": (
        (r"triple\s+c", 2),
        (r"ccc", 2),
        (r"c[\s\-]*syrup", 2),
        (r"phense", 2),
        (r"rondec", 2),
        (r"robo", 1),
        (r"robitussin", 2),
        (r"coricidin", 2),
    ),
    "MDMA / Ecstasy": (
        (r"skittles?", 1),
        (r"rolls?", 1),
        (r"beans?", 1),
        (r"love\s+drug", 2),
        (r"\be\b", 1),
        (r"vitamin\s+e", 2),
    ),
    "Pregabalin / Gabapentin": (
        (r"gabapentin", 2),
        (r"neurontin", 2),
        (r"gabbas", 2),
        (r"lyrica", 2),
        (r"pregabs", 2),
        (r"budweiser\s+pills", 2),
        (r"football", 1),
    ),
    "Misused stimulants / performance enhancers": (
        (r"modafinil", 2),
        (r"provigil", 2),
        (r"armodafinil", 2),
        (r"nuvigil", 2),
        (r"adrafinil", 2),
        (r"phenylpiracetam", 2),
        (r"fonturacetam", 2),
        (r"yohimbine", 2),
        (r"rauwolscine", 2),
        (r"alpha[\s\-]*y", 2),
        (r"dmha", 2),
        (r"octodrine", 2),
        (r"dmaa", 2),
        (r"geranium\s+extract", 1),
        (r"eria\s+jarensis", 2),
        (r"halostachine", 2),
        (r"synephrine", 2),
        (r"bitter\s+orange", 1),
        (r"higenamine", 2),
        (r"nelumbo\s+nucifera", 1),
        (r"clenbuterol", 2),
        (r"clen", 1),
        (r"spiropent", 2),
        (r"ventipulmin", 2),
        (r"salbutamol", 2),
        (r"ventolin", 2),
        (r"terbutaline", 2),
        (r"bricanyl", 2),
        (r"ephedrine", 2),
        (r"eca\s+stack", 2),
        (r"pseudoephedrine", 2),
        (r"sudafed", 2),
        (r"phenylephrine", 2),
        (r"neo[\s\-]*synephrine", 2),
        (r"propylhexedrine", 2),
        (r"benzedrex", 2),
        (r"levomethamphetamine", 2),
        (r"vicks\s+inhaler", 1),
        (r"racepinephrine", 2),
        (r"primatene\s+mist", 2),
        (r"theophylline", 2),
        (r"aminophylline", 2),
        (r"caffeine\s+anhydrous", 2),
        (r"guarana", 1),
        (r"yerba\s+mate", 1),
        (r"kola\s+nut", 1),
        (r"green\s+tea\s+extract", 1),
    ),
    "Research nootropics / SARMs / peptides": (
        (r"sunifiram", 2),
        (r"unifiram", 2),
        (r"piracetam", 2),
        (r"nootropil", 2),
        (r"aniracetam", 2),
        (r"oxiracetam", 2),
        (r"coluracetam", 2),
        (r"pramiracetam", 2),
        (r"nefiracetam", 2),
        (r"semax", 2),
        (r"selank", 2),
        (r"bpc[\s\-]*157", 2),
        (r"tb[\s\-]*500", 2),
        (r"melanotan\s*(?:ii|2)", 2),
        (r"barbie\s+doll", 1),
        (r"cjc[\s\-]*1295", 2),
        (r"ipamorelin", 2),
        (r"mk[\s\-]*677", 2),
        (r"ibutamoren", 2),
        (r"rad[\s\-]*140", 2),
        (r"testolone", 2),
        (r"ostarine", 2),
        (r"enobosarm", 2),
        (r"lgd[\s\-]*4033", 2),
        (r"ligandrol", 2),
        (r"gw[\s\-]*501516", 2),
        (r"cardarine", 2),
        (r"sr[\s\-]*9009", 2),
        (r"stenabolic", 2),
    ),
    "Ketamine": (
        (r"keta", 2),
        (r"\bk\b", 1),
        (r"kit[\s\-]*kat", 1),
        (r"horse\s+tranq", 2),
        (r"horse\s+tranquilizer", 2),
    ),
    "Cocaine / Crack": (
        (r"charlie", 1),
        (r"blow", 1),
        (r"white\s+lady", 2),
        (r"yayo", 2),
        (r"peruvian\s+flake", 2),
        (r"fishscale", 2),
        (r"fish\s+scale", 2),
        (r"rocks?", 1),
    ),
    "LSD / Psychedelics": (
        (r"acid\s+tabs?", 2),
        (r"lsd\s+tabs?", 2),
        (r"blotters?", 2),
        (r"stamps?", 1),
        (r"window\s+pane", 2),
        (r"microdots?", 2),
        (r"sunshine", 1),
        (r"jadoo", 1),
        (r"khumbi", 1),
        (r"fly\s+agaric", 2),
        (r"amanita", 2),
    ),
    "Datura / Scopolamine / Deliriants": (
        (r"datura", 2),
        (r"dhatu+ra", 2),
        (r"thorn\s+apple", 2),
        (r"jimson\s+weed", 2),
        (r"devil'?s\s+breath", 2),
        (r"scopolamine", 2),
        (r"burundanga", 2),
    ),
    "GHB / GBL / 1,4-BDO": (
        (r"ghb", 2),
        (r"liquid\s+g", 2),
        (r"gbl", 2),
        (r"1[\s,\-]*4[\s\-]*bdo", 2),
        (r"1[\s,\-]*4[\s\-]*butanediol", 2),
        (r"gamma[\s\-]*hydroxybutyrate", 2),
        (r"gamma[\s\-]*butyrolactone", 2),
        (r"georgia\s+home\s+boy", 2),
        (r"fantasy", 1),
        (r"soap", 1),
    ),
    "Synthetic cannabinoids / Spice / K2": (
        (r"synthetic\s+cannabinoids?", 2),
        (r"synthetic\s+marijuana", 2),
        (r"potpourri", 2),
    ),
    "Nitrites / Poppers": (
        (r"poppers?", 2),
        (r"amyl\s+nitrite", 2),
        (r"alkyl\s+nitrites?", 2),
        (r"locker\s+room", 1),
        (r"snappers?", 1),
        (r"rush", 1),
    ),
    "Nitrous oxide": (
        (r"nitrous\s+oxide", 2),
        (r"laughing\s+gas", 2),
        (r"whippets?", 2),
        (r"nangs?", 2),
        (r"n2o", 2),
        (r"balloons?", 1),
    ),
    "Inhalants / Solvents": (
        (r"glue", 2),
        (r"dendrite", 2),
        (r"paint\s+thinner", 2),
        (r"petrol\s+sniff(?:ing)?", 2),
        (r"correction\s+fluid", 2),
        (r"white[\s\-]*out", 2),
    ),
    "Hooch / Kachi sharab / Tharra (illicit moonshine)": (
        (r"katchi\s+sharab", 2),
        (r"pakki\s+sharab", 2),
        (r"landa", 1),
        (r"mahua", 1),
        (r"toddy", 1),
        (r"arrack", 2),
        (r"homebrew", 2),
    ),
    "Alcohol": (
        (r"murree\s+beer", 2),
        (r"booze", 2),
        (r"pre[\s\-]*mix", 1),
        (r"liquid\s+courage", 2),
    ),
    "Smokeless tobacco (Naswar / Gutka / Chaalia / Mainpuri)": (
        (r"zarda", 2),
        (r"paan", 1),
        (r"pan\s+masala", 2),
        (r"betel\s+leaf", 1),
        (r"betel\s+nut", 1),
        (r"betel\s+quid", 2),
        (r"supari", 2),
        (r"katha", 1),
        (r"chuna", 1),
        (r"meetha\s+paan", 2),
        (r"saada\s+paan", 2),
        (r"fire\s+paan", 2),
        (r"banarasi\s+paan", 2),
        (r"calcutta\s+paan", 2),
        (r"maghai\s+paan", 2),
        (r"desi\s+paan", 2),
    ),
    "Nicotine / Vape / Tobacco": (
        (r"hookah", 2),
        (r"huqqa", 2),
        (r"narghile", 2),
        (r"shisha\s+bar", 2),
        (r"mu'?assel", 2),
        (r"bidi", 2),
        (r"e[\s\-]*cig", 2),
        (r"e[\s\-]*liquid", 2),
        (r"nic\s+salt", 2),
        (r"juul", 2),
        (r"vape\s+pen", 2),
        (r"nicotine\s+pouches?", 2),
        (r"zyn", 2),
        (r"velo", 2),
        (r"lyft", 2),
        (r"general\s+snus", 2),
        (r"dissolvable\s+nicotine", 2),
        (r"camel\s+orbs", 2),
        (r"nicotine\s+gum", 2),
        (r"nicorette", 2),
        (r"nicotine\s+patch", 2),
        (r"nicoderm", 2),
        (r"nicotine\s+lozenge", 2),
        (r"nicotine\s+spray", 2),
        (r"nicotrol\s+ns", 2),
        (r"nicotine\s+inhaler", 2),
        (r"nicotrol\s+inhaler", 2),
        (r"tambaku", 2),
        (r"e[\s\-]*hookah", 2),
        (r"herbal\s+shisha", 2),
        (r"cloud\s+chasing", 1),
        (r"trick\s+vaping", 1),
        (r"buzz", 1),
        (r"cartridge", 1),
        (r"cart", 1),
        (r"mod", 1),
    ),
    "Cannabis / Charas": (
        (r"afghani", 1),
        (r"chitrali", 1),
        (r"swati", 1),
        (r"black\s+gold", 1),
        (r"red\s+lebanese", 2),
        (r"blonde", 1),
        (r"cream", 1),
        (r"chillum", 1),
        (r"bong", 1),
        (r"spliff", 2),
        (r"doobie", 2),
        (r"reefer", 2),
        (r"grass", 1),
        (r"herb", 1),
        (r"bud", 1),
        (r"flower", 1),
        (r"dabs?", 2),
        (r"wax", 1),
        (r"shatter", 2),
        (r"edibles?", 2),
        (r"brownies", 1),
        (r"space\s+cake", 2),
        (r"tincture", 1),
        (r"cbd\s+oil", 2),
        (r"hemp", 1),
        (r"kief", 2),
        (r"dry\s+sift", 2),
        (r"bubble\s+hash", 2),
        (r"rosin", 1),
        (r"live\s+resin", 2),
        (r"distillate", 1),
    ),
}


REGIONAL_FUZZY_ALIAS_TARGETS: Tuple[Tuple[str, str], ...] = (
    ("captagon", "Synthetic stimulants / Cathinones / Captagon"),
    ("kaanch", "Ice / Methamphetamine"),
    ("xanies", "Unprescribed Xanax / Benzodiazepines"),
    ("vallies", "Unprescribed Xanax / Benzodiazepines"),
    ("rivotril", "Unprescribed Xanax / Benzodiazepines"),
    ("trama", "Unprescribed opioid pills / Tramadol"),
    ("dendrite", "Inhalants / Solvents"),
    ("whippets", "Nitrous oxide"),
    ("datura", "Datura / Scopolamine / Deliriants"),
    ("dilaudid", "Heroin / Opioids"),
    ("morphine", "Heroin / Opioids"),
    ("methadone", "Heroin / Opioids"),
    ("fentanyl", "Heroin / Opioids"),
    ("carfentanil", "Heroin / Opioids"),
    ("oxycontin", "Unprescribed opioid pills / Tramadol"),
    ("oxycodone", "Unprescribed opioid pills / Tramadol"),
    ("hydrocodone", "Unprescribed opioid pills / Tramadol"),
    ("tapentadol", "Unprescribed opioid pills / Tramadol"),
    ("kratom", "Atypical opioids / Kratom / Tianeptine"),
    ("tianeptine", "Atypical opioids / Kratom / Tianeptine"),
    ("phenibut", "Sedatives / Z-drugs / Barbiturates / Muscle relaxants"),
    ("zolpidem", "Sedatives / Z-drugs / Barbiturates / Muscle relaxants"),
    ("gabapentin", "Pregabalin / Gabapentin"),
    ("pregabalin", "Pregabalin / Gabapentin"),
    ("modafinil", "Misused stimulants / performance enhancers"),
    ("clenbuterol", "Misused stimulants / performance enhancers"),
    ("ephedrine", "Misused stimulants / performance enhancers"),
    ("nicotine", "Nicotine / Vape / Tobacco"),
    ("supari", "Smokeless tobacco (Naswar / Gutka / Chaalia / Mainpuri)"),
)


# Deliberately inactive until a stronger regional source is available or the
# team decides to accept the false-positive risk for these terms.
TERMS_HELD_FOR_REVIEW: Tuple[str, ...] = (
    "Malala",
    "Base",
    "Lines",
    "Juice",
    "Pipe",
    "Meth",
    "Oil",
    "Seeds",
    "Clone",
    "Grow",
    "Harvest",
    "Cure",
    "Trim",
    "Commit",
    "Coal",
    "Quick Light",
    "Natural Coal",
    "Foil",
    "HMD",
    "Kaloud",
    "Hose",
    "Tip",
    "Bowl",
    "Phunnel",
    "Egyptian Bowl",
    "Vortex Bowl",
    "Stem",
    "Purge Valve",
    "Grommet",
    "Diffuser",
    "Ice Hose",
    "Wind Cover",
    "Carry Case",
    "Steam Stone",
    "Beamer",
    "Ashtray",
    "Tongs",
    "Brush",
    "Blender",
    "Session",
    "Head Change",
)
